name: Data Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pandas jsonschema

      - name: Check modified files
        run: |
            MODIFIED_FILES=$(git diff --name-only origin/main...HEAD)
            ERROR=false
            for FILE in $MODIFIED_FILES
            do
              FILENAME=$(basename $FILE)
              if [[ $FILENAME != "common_libraries.tsv" && $FILENAME != "common_samples.tsv" ]]
              then
                echo -e "\e[31mInvalid file modified: $FILE\e[0m"
                ERROR=true
              fi
            done
            if $ERROR
            then
              exit 1
            fi
            MODIFIED_FILES=$(echo $MODIFIED_FILES | tr '\n' ' ')
            echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
            echo -e "\033[38;5;40mNo modified files except data\033[0m"

      - name: Check old rows in modified tsv; Validate jsonschema
        run: |
            MODIFIED_FILES=(${{ env.MODIFIED_FILES }})
            for FILE in "${MODIFIED_FILES[@]}"
            do
              if [[ $FILE == *"common_libraries.tsv"* ]]; then
                export FILE_PATH=${{ github.workspace }}/$FILE
                python scripts/check_modified_libraries.py
              elif [[ $FILE == *"common_samples.tsv"* ]]; then
                export FILE_PATH=${{ github.workspace }}/$FILE
                python scripts/check_modified_samples.py
              fi
            done

      - name: Save df_pr_check and df_fork_check as artifacts
        uses: actions/upload-artifact@v2
        with:
         name: comparison-results
         path: |
            df_pr_check.csv
            df_fork_check.csv