name: Updating the map

on:
  push:
    branches:
      - main
    paths:
      - 'common_samples/common_samples.tsv'

jobs:
  update_map:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib cartopy folium

    - name: Run map visualization script
      run: |
        python scripts/map.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://${{secrets.MAP_METAGENOME}}@github.com/agni-bioinformatics-lab/OilMetagenomesDB.git
        git add README.md assets/image/git_img_map.png index.html
        git commit -m "Update map visualization in README.md"
        git push