name: SRS validation

# Trigger this workflow on successful data_validation.yml
on:
  workflow_run:
    workflows:
      - Data validation
    types:
      - completed

jobs:

    # Job to validate SRS of data
    check_srs:
        runs-on: ubuntu-latest
          
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # Configure the Python environment  
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            # Install required dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pandas jsonschema

            # Run script validation for SRS data
            - name: Run script validation_srs.py
              run: |
                  python scripts/validation_srs.py
